### ISSUE TITLE
does not detect well

### ISSUE THREAD

**Issue by mahmoudalbardan** [simaiden/Clothing-Detection#1]
Hello,

I downloaded your code and tried to run it on an image from the web but it does not work. It gives me **thousands of bounding boxes**. Are you sure from your training on DeepFashion2? and are you sure of your non maximum suppression function because i found others on the web but still no results.

Thanks in advance

**Comment by simaiden** [comment]
Sorry for the late reply.

Yes I trained with Deepfashion2 but only in users photos. I am updating the repo in the next weeks to add better weights for YOLOv3 and also anothers object detections models.

I tried the image_demo.py with some images and seems to be ok, maybe yo can try to increase the nms threshold and/or the confidence threshold.

Thanks

**Comment by mahmoudalbardan** [comment]
Thank you for your answer!
